# django-core-models project travis config file

language: python
sudo: true

python: '3.6'

services:
  - docker
env:
  global:
    - COMPOSE_VERSION=1.22.0
    - DOCKER_VERSION=17.09.0-ce
    - SERVICE='web-test'

  matrix:
    - TOXENV=py36-django11115
    - TOXENV=py36-django217
 
matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: TOXENV=py27-django11115
    - python: '3.5'
      env: TOXENV=py35-django11115
    - python: '3.5'
      env: TOXENV=py35-django217
    - python: '3.7'
      env: TOXENV=py37-django217 COMPOSE_FILE='docker-sqlite-compose-test.yml'
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=py37-django217 COMPOSE_FILE='docker-mysql-compose-test.yml'
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=py37-django217 COMPOSE_FILE='docker-postgres-compose-test.yml'
      dist: xenial
      sudo: true


before_install:
- if [[ $COMPOSE_FILE ]]; 
  then ./docker/docker_update.sh;
  fi


script:
  - docker version
  - docker-compose version
  - if [ -z "$COMPOSE_FILE" ]; 
    then tox -e $TOXENV;
    else docker-compose -v; docker-compose -f $COMPOSE_FILE up --abort-on-container-exit --exit-code-from $SERVICE || travis_terminate 1;
    fi

install:
  - pip install tox


notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop