# docker-compose mysql configuration file
version: "3"
services:
  db-mysql:
    restart: always
    image: mysql:latest
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3307:3306"
    environment:
    # In a 'real' environment passwords will be defined in the environment
    # by only using the key
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=mysql
    - MYSQL_DATABASE=django_core_models
    
  web-mysql:
    build: 
      context: .
      dockerfile: docker-mysql-dockerfile.yml
    command: docker/run.sh -w 15 -t mysql -d db-mysql
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-mysql
    env_file: 
      - docker/env/common
      - docker/env/dev/mysql
      
  
